### ISSUE TITLE
Walk Speed

### ISSUE THREAD

**Issue by guategeek** [Drakmyth/blender-app-templates#2]
Hey, nice application template. I use the Blender Walk navigation primarily but its a drag to have to keep scrolling the mouse wheel every time I change between a CAD setup file (0.001 unit scale in mm) and a Game Dev setup (1.0 unit scale) so that the movement scale is right.

Would there be a way to add to the script of the CADsketcher setup values for the Walk Speed, and Speed Factor? As these are settings that are global and not saved with a file.

[This post](https://blender.stackexchange.com/questions/230550/python-access-to-walk-speed-setting-of-walk-fly-navigation-mode) might be able to help (I don't know anything about scripting)

**Comment by Drakmyth** [comment]
I looked into this a bit and it looks like Application Templates can only modify [a couple types of preferences](https://docs.blender.org/manual/en/dev/advanced/app_templates.html#details) (specifically Themes, Add-ons, Keymaps, and Viewport lighting). Seems like a pretty big limitation to me, but 🤷.

To change any other preferences you'd need to create an `__init__.py` that uses handlers to set the values, then place that `__init__.py` file alongside the other files for the installed template. There's an example of how to do this [in the Application Template documentation](https://docs.blender.org/manual/en/dev/advanced/app_templates.html#template-scripts) and I think the handler you would want to use is either [bpy.app.handlers.load_pre](https://docs.blender.org/api/current/bpy.app.handlers.html#bpy.app.handlers.load_pre) or [bpy.app.handlers.load_post](https://docs.blender.org/api/current/bpy.app.handlers.html#bpy.app.handlers.load_post).

I'd rather not add such a script to this repo unless it's a change that very likely everyone using the template will want, but it looks like it should absolutely be possible and you should be able to create the script and just drop it in the template folder to make it apply to all newly created files that use that template.
